version: '3'

services:
  mysql:
    image: mysql:8.0.32
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
    ports:
    - 3306:3306

  fluentd:
    build:
      context: .
      dockerfile: resources/fluentd/Dockerfile
    environment:
      FLUENTD_CONF: fluentd.conf
      TZ: Asia/Tokyo
    volumes:
      - ./logs:/fluentd/log
      - ./resources/fluentd/etc:/fluentd/etc

  elasticsearch:
    image: elasticsearch:8.6.2

    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - xpack.monitoring.collection.enabled=true
      - ELASTIC_PASSWORD=P@ssw0rd

  kibana:
    image: kibana:8.6.2
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    restart: always