global:
  scrape_interval: 15s
  external_labels:
    monitor: 'example-prometheus'
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'rust-app'
    static_configs:
      - targets: ['host.docker.internal:8080']
  